### ISSUE TITLE
Staking rewards not received .

### ISSUE THREAD

**Issue by jefferylabelle** [bitcoin-atom/bitcoin-atom#11]
Hello, 
I've had a balance in my atom wallet for over 7 days. 
I still have not received any staking rewards. 
using the listminting cmd , I see that I should have been receiving rewards. could someone check on this for me ? I have copied and pasted a few of the transactions found, there are many.  
--------------------------------------------------------------------------------------------------

Copied from console : 
--------------------------------------------------------------------------------------------------
"account": "Moon",
    "address": "AbzoJ9JQSqRJZpP5KsqyddFCvgAa6y2kkh",
    "txid": "d3136da6ee74d240f98229c8a2e9da4e97b51be67610e2caf9f29d8223c12800",
    "vout": 1,
    "time": 1521112440,
    "amount": 1.08427628,
    "status": "mature",
    "age-in-day": 5,
    "coin-day-weight": 3,
    "minting-probability-10min": 6.984810319021761e-007,
    "minting-probability-24h": 0.0001005762456028902,
    "minting-probability-30d": 0.01233502501255546,
    "minting-probability-90d": 0.09127537090474258,
    "attempts": 341055
  },
  {
    "account": "Moon",
    "address": "AbzoJ9JQSqRJZpP5KsqyddFCvgAa6y2kkh",
    "txid": "65ad1d8ba48f3f37b693f85dcea02ac1d43f80673a5e4a8a8dc3603a5219570c",
    "vout": 0,
    "time": 1521416051,
    "amount": 1.01339508,
    "status": "mature",
    "age-in-day": 2,
    "coin-day-weight": 0,
    "minting-probability-10min": 1.396962457933526e-007,
    "minting-probability-24h": 2.011605847573872e-005,
    "minting-probability-30d": 0.009310448119577375,
    "minting-probability-90d": 0.07992623794307441,
    "attempts": 37444

    "account": "Moon",
    "address": "AbzoJ9JQSqRJZpP5KsqyddFCvgAa6y2kkh",
    "txid": "e9c43f88d2653cfc50afe37f8966a1ae69db3ec9908d3b5b05b7ef4c02ac9863",
    "vout": 0,
    "time": 1520992857,
    "amount": 10.70979525,
    "status": "mature",
    "age-in-day": 7,
    "coin-day-weight": 53,
    "minting-probability-10min": 9.359605331993315e-006,
    "minting-probability-24h": 0.001346881614906814,
    "minting-probability-30d": 0.1257040916710075,
    "minting-probability-90d": 0.6239800276754204,
    "attempts": 460638
  },
  {
    "account": "Moon",
    "address": "AbzoJ9JQSqRJZpP5KsqyddFCvgAa6y2kkh",
    "txid": "7dada163d545d29ec954e77c8bb59c429d4591890ccbb0d945343c3413328c68",
    "vout": 0,
    "time": 1521007299,
    "amount": 10.38071543,
    "status": "mature",
    "age-in-day": 7,
    "coin-day-weight": 51,
    "minting-probability-10min": 8.800825369026377e-006,
    "minting-probability-24h": 0.001266521713433999,
    "minting-probability-30d": 0.1211547043684648,
    "minting-probability-90d": 0.6113757975735659,
    "attempts": 446196

**Comment by gonzzza007** [comment]
Same issue. Waited for a week - no reward.

**Comment by rootSig** [comment]
Hi @jefferylabelle and @gonzzza007, please check out the minting-probability parameters - these describe the actual possibility of receiving staking rewards.

As per the atomd output provided above:

"minting-probability-10min": 8.800825369026377e-006,
"minting-probability-24h": 0.001266521713433999,
"minting-probability-30d": 0.1211547043684648,
"minting-probability-90d": 0.6113757975735659,

The staking probability in your case is still low, which is described by these values.

Closing the issue for now. Please reopen if needed.
