### ISSUE TITLE
atomd / linux / high memory usage (and growing)

### ISSUE THREAD

**Issue by gonzzza007** [bitcoin-atom/bitcoin-atom#14]
I have tried to run atomd on my Ubuntu system and it crashed twice due to constantly growing memory usage. Running bitcoin node on the same server had no issues. I can dig up more details if you're interested and still developing your software.

**Comment by rootSig** [comment]
Hi @gonzzza007, please share your BCA logs (debug log) at the moment of the crash.

This is most likely due to thread-stake-minter. Try running atomd with stakegen=0 at atom.conf (or pass as a command-line parameter).

Please let us know if this helps to reduce memory usage.

**Comment by rootSig** [comment]
No additional input received. Closing issue now.

Please reopen if this issue persists.
