### ISSUE TITLE
MacOS rename application 

### ISSUE THREAD

**Issue by sherkhan** [bitcoin-atom/bitcoin-atom#15]
Atom-qt looks not good
Bitcoin Atom will be better
https://yadi.sk/i/uMq02daN3TreSq

**Comment by rootSig** [comment]
Thanks for reporting @sherkhan, macOS appname to be changed in the next release v0.16.x

**Comment by rootSig** [comment]
Closed in the most recent release Bitcoin Atom v0.16.0
