### ISSUE TITLE
wallet is not singkron

### ISSUE THREAD

**Issue by miftah1399** [bitcoin-atom/bitcoin-atom#17]
wallet is not singkron
I have long downloaded 
and installed wallet windows but it is almost 7 days still not sync, please help
![screenshot_2](https://user-images.githubusercontent.com/31036586/38565349-455bbcca-3d0b-11e8-9882-324fc92dbe43.jpg)

**Comment by rootSig** [comment]
Hi @miftah1399, from what I can see on your screenshot, your BCA wallet is syncing with the current progress of 68.93%.

Everything looks working according to the pic, closing the issue now.

Please reopen in case any further issue occurs.
