### ISSUE TITLE
Compile error when trying to compile the last Master branch

### ISSUE THREAD

**Issue by satoshi-ninja** [bitcoin-atom/bitcoin-atom#2]
Compile error when trying to compile the last Master branch:

`Making all in src`
`make[1]: Entering directory '/opt/bitcoin-atom/src'`
`make[2]: Entering directory '/opt/bitcoin-atom/src'`
`make[3]: Entering directory '/opt/bitcoin-atom'`
`make[3]: Leaving directory '/opt/bitcoin-atom'`
`make[3]: Entering directory '/opt/bitcoin-atom/src/secp256k1'`
`make[3]: Leaving directory '/opt/bitcoin-atom/src/secp256k1'`
`  CXX      test/test_test_bitcoin-pow_tests.o`
`In file included from /usr/include/boost/test/unit_test.hpp:19:0,`
`                 from test/pow_tests.cpp:12:`
`test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work::test_method()’:`
`test/pow_tests.cpp:25:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]`
`     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00d86a);`
`                                                                                                            ^`
`In file included from ./chain.h:9:0,`
`                 from test/pow_tests.cpp:5:`
`./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arith_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}`
`     ^`
`In file included from /usr/include/boost/test/unit_test.hpp:19:0,`
`                 from test/pow_tests.cpp:12:`
`test/pow_tests.cpp:25:108: error: cannot convert ‘const Consensus::Params’ to ‘int64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(arith_uint256, int64_t, int64_t, const Consensus::Params&)’`
`     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00d86a);`
`                                                                                                            ^`
`test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work_pow_limit::test_method()’:`
`test/pow_tests.cpp:37:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]`
`     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00ffff);`
`                                                                                                            ^`
`In file included from ./chain.h:9:0,`
`                 from test/pow_tests.cpp:5:`
`./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arith_uint256(uint64_t)’`
`     arith_uint256(uint64_t b) : base_uint<256>(b) {}`
`     ^`
`In file included from /usr/include/boost/test/unit_test.hpp:19:0,`
`                 from test/pow_tests.cpp:12:`
`test/pow_tests.cpp:37:108: error: cannot convert ‘const Consensus::Params’ to ‘int64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(arith_uint256, int64_t, int64_t, const Consensus::Params&)’`
`     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00ffff);`
`                                                                                                            ^`
`test/pow_tests.cpp: In member function ‘void pow_tests::get_next_work_lower_limit_actual::test_method()’:`
`test/pow_tests.cpp:49:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]`
`     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1c0168fd);`
`                                                                                                            ^`
`In file included from ./chain.h:9:0,`
`                 from test/pow_tests.cpp:5:`
`./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arith_uint256(uint64_t)’`
`     arith_uint256(uint64_t b) : base_uint<256>(b) {}`
`     ^`
`In file included from /usr/include/boost/test/unit_test.hpp:19:0,`
`                 from test/pow_tests.cpp:12:`
`test/pow_tests.cpp:49:108: error: cannot convert ‘const Consensus::Params’ to ‘int64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(arith_uint256, int64_t, int64_t, const Consensus::Params&)’`
`     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1c0168fd);`
`                                                                                                            ^`
`test/pow_tests.cpp: In member function ‘void` `pow_tests::get_next_work_upper_limit_actual::test_method()’:`
`test/pow_tests.cpp:61:108: error: invalid conversion from ‘CBlockIndex*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]`
`     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00e1fd);`
`                                                                                                            ^`
`In file included from ./chain.h:9:0,`
`                 from test/pow_tests.cpp:5:`
`./arith_uint256.h:267:5: note:   initializing argument 1 of ‘arith_uint256::arith_uint256(uint64_t)’
     arith_uint256(uint64_t b) : base_uint<256>(b) {}`
`     ^`
`In file included from /usr/include/boost/test/unit_test.hpp:19:0,`
`                 from test/pow_tests.cpp:12:`
`test/pow_tests.cpp:61:108: error: cannot convert ‘const Consensus::Params’ to ‘int64_t {aka long int}’ for argument ‘3’ to ‘uint32_t CalculateNextWorkRequired(arith_uint256, int64_t, int64_t, const Consensus::Params&)’`
`     BOOST_CHECK_EQUAL(CalculateNextWorkRequired(&pindexLast, nLastRetargetTime, chainParams->GetConsensus()), 0x1d00e1fd);`
`                                                                                                            ^`
`Makefile:9326: recipe for target 'test/test_test_bitcoin-pow_tests.o' failed`
`make[2]: *** [test/test_test_bitcoin-pow_tests.o] Error 1`
`make[2]: Leaving directory '/opt/bitcoin-atom/src'`
`Makefile:9906: recipe for target 'all-recursive' failed`
`make[1]: *** [all-recursive] Error 1`
`make[1]: Leaving directory '/opt/bitcoin-atom/src'`
`Makefile:747: recipe for target 'all-recursive' failed`
`make: *** [all-recursive] Error 1`
`

**Comment by pav-hash** [comment]
./configure --enable-tests=false

This will at least get you past the cast error and allow you to compile..

**Comment by satoshi-ninja** [comment]
Thanks @pavesi5 it worked! :)
