### ISSUE TITLE
Missed zeros in the commission

### ISSUE THREAD

**Issue by nimfarit** [bitcoin-atom/bitcoin-atom#6]
![1](https://user-images.githubusercontent.com/24655739/37338437-8266dea0-26c8-11e8-9747-ec76b991b9d8.png)
![2](https://user-images.githubusercontent.com/24655739/37338438-8286b5c2-26c8-11e8-89fa-39452311c7f8.png)

**Comment by rootSig** [comment]
fixed by commit #f7feff8e7edcc84c047684a8173a06d5858872c3

please update to the latest version (v0.15.99.5 as of now)
